minimumReleaseAgeExclude:
  - '@vitest/expect@4.1.7'
  - '@vitest/mocker@4.1.7'
  - '@vitest/pretty-format@4.1.7'
  - '@vitest/runner@4.1.7'
  - '@vitest/snapshot@4.1.7'
  - '@vitest/spy@4.1.7'
  - '@vitest/utils@4.1.7'
  - vitest@4.1.7
  - '@tanstack/virtual-core@3.15.0'
  - '@tanstack/vue-virtual@3.13.25'
  - devframe@0.4.1
shellEmulator: true

trustPolicy: no-downgrade
packages:
  - .
  - ui
overrides:
  chokidar: ^5.0.0
  semver: ^7.8.0
catalog:
  '@antfu/eslint-config': ^9.0.0
  '@clack/prompts': ^1.4.0
  '@iconify-json/carbon': ^1.2.21
  '@iconify-json/octicon': ^1.2.24
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/ri': ^1.2.10
  '@octokit/plugin-retry': ^8.1.0
  '@octokit/plugin-throttling': ^11.0.3
  '@playwright/test': ^1.60.0
  '@tanstack/vue-virtual': ^3.13.25
  '@types/node': ^25.9.1
  '@unocss/nuxt': ^66.6.8
  '@unocss/preset-web-fonts': ^66.6.8
  '@unocss/reset': ^66.6.8
  '@vitest/coverage-v8': 4.0.18
  '@vueuse/nuxt': ^14.3.0
  ansis: ^4.3.0
  bumpp: ^11.1.0
  cac: ^7.0.0
  colorjs.io: ^0.6.1
  devframe: ^0.4.1
  dotenv: ^17.4.2
  eslint: ^10.4.0
  floating-vue: ^5.2.2
  jiti: ^2.7.0
  lint-staged: ^17.0.5
  listhen: ^1.10.0
  marked: ^18.0.4
  nostics: ^0.2.0
  nuxt: ^4.4.6
  octokit: ^5.0.5
  ohash: ^2.0.11
  open: ^11.0.0
  parse-diff: ^0.12.0
  pathe: ^2.0.3
  portless: ^0.13.0
  reka-ui: ^2.9.7
  shiki: ^4.1.0
  simple-git-hooks: ^2.13.1
  skills-npm: ^1.1.1
  splitpanes: ^4.0.4
  tsdown: ^0.22.0
  tsx: ^4.22.3
  typescript: ^6.0.3
  unimport: ^6.3.0
  unocss: ^66.6.8
  valibot: ^1.4.0
  vitest: ^4.1.7
  vue-data-ui: ^3.19.9
  vue-tsc: ^3.3.1
  whenexpr: ^0.1.2
  yaml: ^2.9.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - vue-demi
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  simple-git-hooks: true
  vue-demi: true
