export const selectors = {
  navbar: '[data-testid="navbar"]',
  navbarRepo: '[data-testid="navbar-repo"]',
  navbarTabIssues: '[data-testid="navbar-tab-issues"]',
  navbarTabPulls: '[data-testid="navbar-tab-pulls"]',
  navbarSearch: '[data-testid="navbar-search"]',
  itemList: '[data-testid="item-list"]',
  itemRow: '[data-testid="item-row"]',
  detailPanel: '[data-testid="detail-panel"]',
  detailTitle: '[data-testid="detail-title"]',
  queueBadge: '[data-testid="queue-badge"]',
  queuePanel: '[data-testid="queue-panel"]',
  queueEntry: '[data-testid="queue-entry"]',
  helpOverlay: '[data-testid="help-overlay"]',
  labelEditor: '[data-testid="label-editor"]',
  hubProjectCard: '[data-testid="hub-project-card"]',
  hubProjectPicker: '[data-testid="hub-project-picker"]',
}
