// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = 'Anthony Fu'
export const name = 'vscode-ghfs'
export const version = '0.0.3'
export const displayName = undefined
export const description = 'GitHub issues/PRs as filesystem, for offline view and operations in batch. Designed for human and agents.'
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey = never

/**
 * Commands map registered by `Anthony Fu.vscode-ghfs`
 */
export const commands = {
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey = never

export interface ConfigKeyTypeMap {
}

export interface ConfigShorthandMap {
}

export interface ConfigShorthandTypeMap {
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T
  default: ConfigKeyTypeMap[T]
}

/**
 * Configs map registered by `Anthony Fu.vscode-ghfs`
 */
export const configs = {
}

export interface ScopedConfigKeyTypeMap {
}

export const scopedConfigs = {
  scope: 'ghfs',
  defaults: {
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
}

export interface NestedScopedConfigs {
}
