import { createLocalFontProcessor } from '@unocss/preset-web-fonts/local'
import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetWebFonts,
  presetWind3,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

export default defineConfig({
  presets: [
    presetWind3(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      extraProperties: {
        'display': 'inline-block',
        'vertical-align': 'middle',
      },
    }),
    presetTypography(),
    presetWebFonts({
      fonts: {
        sans: 'DM Sans:200,400,500,700',
        mono: 'DM Mono:300,400,500',
      },
      processors: createLocalFontProcessor(),
    }),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
  shortcuts: [
    {
      'color-base': 'color-neutral-800 dark:color-neutral-300',
      'color-muted': 'color-neutral-500 dark:color-neutral-500',
      'color-faint': 'color-neutral-400 dark:color-neutral-600',
      'color-active': 'color-primary-600 dark:color-primary-400',
      'bg-base': 'bg-white dark:bg-#111',
      'bg-secondary': 'bg-#eee dark:bg-#222',
      'bg-active': 'bg-#8881',
      'bg-tooltip': 'bg-white/75 dark:bg-#111/75 backdrop-blur-8',
      'border-base': 'border-neutral-200 dark:border-neutral-800',
      'border-active': 'border-primary-600/25 dark:border-primary-400/25',
      'bg-glass': 'bg-white/70 dark:bg-#111/70 backdrop-blur-8 border border-base',
      'btn-action': 'border border-base rounded flex gap-2 items-center px2 py1 op75 hover:op100 hover:bg-active disabled:pointer-events-none disabled:op30!',
      'btn-circle': 'w-10 h-10 rounded-full flex items-center justify-center op75 hover:op100 hover:bg-active transition disabled:pointer-events-none disabled:op30',
      'btn-primary': 'px3 py1.5 rounded flex gap-2 items-center text-sm bg-primary-500 hover:bg-primary-600 text-white transition disabled:op50 disabled:pointer-events-none',
      'op-fade': 'op65',
      'page-padding': 'pt-24 pl-112 pr-24 pb-8',
      'page-padding-collapsed': 'pt-24 pl-16 pr-24 pb-8',
      'sidepanel': 'fixed left-4 top-22 w-100 bg-glass rounded-1em shadow',
      'nav-right': 'fixed right-4 top-4 z-40 flex items-center gap-2 bg-glass rounded-full shadow px2 py2',
      'kbd': 'px-1.5 py-0.5 rounded border border-base bg-secondary font-mono text-xs color-muted',
      'badge': 'inline-flex items-center px-1.5 py-0.5 rounded text-xs font-medium',
      'hover-fade': 'op0 group-hover:op100 transition',
    },
    [/^badge-color-(\w+)$/, ([, color]) => `badge bg-${color}-400/20 dark:bg-${color}-400/10 text-${color}-700 dark:text-${color}-300`],
    [/^bg-glass-(\d+)$/, ([, n]) => `bg-white/${n} dark:bg-#111/${n} backdrop-blur-8 border border-base`],
  ],
  theme: {
    colors: {
      primary: {
        50: '#eef6ff',
        100: '#d9eaff',
        200: '#bcdaff',
        300: '#8ec2ff',
        400: '#589fff',
        500: '#3b82f6',
        600: '#2563eb',
        700: '#1d4ed8',
        800: '#1e40af',
        900: '#1e3a8a',
      },
    },
  },
  safelist: [
    'badge-color-green',
    'badge-color-purple',
    'badge-color-orange',
    'badge-color-red',
    'badge-color-blue',
    'badge-color-yellow',
    'badge-color-pink',
    'badge-color-neutral',
    'i-carbon-chevron-up',
    'i-carbon-chevron-down',
    'i-carbon-renew',
    'i-carbon-play-filled-alt',
    'i-carbon-list-checked',
    'i-carbon-trash-can',
    'i-carbon-warning',
    'i-carbon-launch',
    'i-carbon-close',
    'i-carbon-search',
    'i-carbon-filter',
    'i-carbon-cloud-download',
    'i-carbon-restart',
    'i-ph-moon-duotone',
    'i-ph-sun-duotone',
    'i-ph-github-logo-duotone',
    'i-ph-arrow-circle-up-duotone',
    'i-ph-arrow-circle-down-duotone',
    'i-ph-list-bullets-duotone',
    'i-ph-circle-dashed',
    'i-ph-play-circle-duotone',
    'i-ri-git-pull-request-fill',
    'i-ri-bug-fill',
  ],
})
