import { createLocalFontProcessor } from '@unocss/preset-web-fonts/local'
import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetWebFonts,
  presetWind3,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

export default defineConfig({
  presets: [
    presetWind3(),
    presetAttributify(),
    presetIcons({
      scale: 1.0,
      extraProperties: {
        'display': 'inline-block',
        'vertical-align': 'middle',
      },
    }),
    presetTypography(),
    presetWebFonts({
      fonts: {
        sans: 'DM Sans:200,400,500,700',
        mono: 'DM Mono:300,400,500',
      },
      processors: createLocalFontProcessor(),
    }),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
  shortcuts: [
    {
      'color-base': 'text-[#1f2328] dark:text-[#e6edf3]',
      'color-muted': 'text-[#59636e] dark:text-[#8b949e]',
      'color-faint': 'text-[#818b98] dark:text-[#6e7681]',
      'color-active': 'color-primary-600 dark:color-primary-400',
      'bg-base': 'bg-white dark:bg-black',
      'bg-secondary': 'bg-[#f6f8fa] dark:bg-[#151b23]',
      'bg-subtle': 'bg-[#f6f8fa] dark:bg-[#161b22]',
      'bg-active': 'bg-[#f3f4f6] dark:bg-[#1c2128]',
      'bg-selected': 'bg-[#0969da]/10 dark:bg-[#0969da]/20',
      'bg-tooltip': 'bg-white/90 dark:bg-[#0d1117]/90 backdrop-blur-8',
      'border-base': 'border-[#d1d9e0] dark:border-[#3d444d]',
      'border-muted': 'border-[#d1d9e0b3] dark:border-[#3d444db3]',
      'border-active': 'border-primary-500/40 dark:border-primary-400/40',
      'bg-glass': 'bg-white/80 dark:bg-[#0d1117]/80 backdrop-blur-8 border border-base',
      'btn-action': 'border border-base rounded flex gap-2 items-center px2 py1 op75 hover:op100 hover:bg-active disabled:pointer-events-none disabled:op30!',
      'btn-icon': 'w-8 h-8 rounded flex items-center justify-center op75 hover:op100 hover:bg-active transition disabled:pointer-events-none disabled:op30',
      'btn-circle': 'w-10 h-10 rounded-full flex items-center justify-center op75 hover:op100 hover:bg-active transition disabled:pointer-events-none disabled:op30',
      'btn-primary': 'px3 py1.5 rounded flex gap-2 items-center text-sm bg-primary-500 hover:bg-primary-600 text-white transition disabled:op50 disabled:pointer-events-none',
      'op-fade': 'op65',
      'kbd': 'inline-flex items-center justify-center h-4 min-w-4 px-1.5 rounded border border-base border-b-2 bg-secondary font-mono text-[10px] color-muted leading-none',
      'badge': 'inline-flex items-center px-1.5 py-0.5 rounded text-xs font-medium',
      'hover-fade': 'op0 group-hover:op100 transition',
      'tab-trigger': 'px-3 py-2 -mb-px flex items-center gap-1.5 text-sm color-muted border-b-2 border-transparent hover:color-active data-[state=active]:color-active data-[state=active]:border-primary-500 dark:data-[state=active]:border-primary-400 transition rounded-t',
      'panel-active': 'relative before:(content-[""] absolute inset-0.5px blur-1.5px border border-primary-400 dark:border-primary-300 pointer-events-none z-100)',
      'tab-count': 'inline-flex items-center px-1.5 min-w-5 h-5 rounded-full bg-subtle text-[10px] font-mono color-muted tabular-nums',
    },
    [/^badge-color-(\w+)$/, ([, color]) => `badge bg-${color}-400/20 dark:bg-${color}-400/10 text-${color}-700 dark:text-${color}-300`],
    [/^bg-glass-(\d+)$/, ([, n]) => `bg-white/${n} dark:bg-#111/${n} backdrop-blur-8 border border-base`],
  ],
  theme: {
    colors: {
      primary: {
        50: '#ddf4ff',
        100: '#b6e3ff',
        200: '#80ccff',
        300: '#54aeff',
        400: '#218bff',
        500: '#0969da',
        600: '#0550ae',
        700: '#033d8b',
        800: '#0a3069',
        900: '#002155',
      },
    },
  },
  safelist: [
    'badge-color-green',
    'badge-color-purple',
    'badge-color-orange',
    'badge-color-red',
    'badge-color-blue',
    'badge-color-yellow',
    'badge-color-pink',
    'badge-color-neutral',
    'badge-color-yellow',
    'i-octicon-mark-github-16',
    'i-octicon-search-16',
    'i-octicon-sync-16',
    'i-octicon-download-16',
    'i-octicon-play-16',
    'i-octicon-list-unordered-16',
    'i-octicon-issue-opened-16',
    'i-octicon-issue-closed-16',
    'i-octicon-git-pull-request-16',
    'i-octicon-git-pull-request-closed-16',
    'i-octicon-git-merge-16',
    'i-octicon-git-pull-request-draft-16',
    'i-octicon-skip-16',
    'i-octicon-x-16',
    'i-octicon-x-circle-16',
    'i-octicon-trash-16',
    'i-octicon-link-external-16',
    'i-octicon-alert-16',
    'i-octicon-sun-16',
    'i-octicon-moon-16',
    'i-octicon-arrow-up-16',
    'i-octicon-arrow-down-16',
    'i-octicon-arrow-up-right-16',
    'i-octicon-arrow-left-16',
    'i-octicon-plus-16',
    'i-octicon-plus-circle-16',
    'i-octicon-comment-16',
    'i-octicon-comment-discussion-16',
    'i-octicon-check-16',
    'i-octicon-check-circle-16',
    'i-octicon-hourglass-16',
    'i-octicon-pencil-16',
    'i-octicon-tag-16',
    'i-octicon-milestone-16',
    'i-octicon-person-16',
    'i-octicon-people-16',
    'i-octicon-inbox-16',
    'i-octicon-question-16',
    'i-octicon-git-commit-16',
    'i-octicon-file-diff-16',
    'i-octicon-check-circle-fill-16',
    'i-octicon-chevron-right-16',
    'i-octicon-chevron-down-16',
    'i-octicon-copy-16',
    'i-octicon-issue-reopened-16',
    'i-octicon-eye-16',
    'i-octicon-eye-closed-16',
    'i-octicon-dot-16',
    'i-octicon-lock-16',
    'i-octicon-history-16',
    'i-octicon-bookmark-16',
    'i-octicon-cross-reference-16',
    'i-octicon-repo-push-16',
  ],
})
